version: '3.9'

services:
  filebeat:
    image: beats/filebeat:${FILEBEAT_VERSION}
    container_name: ${SERVICE_NAME}-filebeat
    hostname: filebeat
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./test-service/logs:/var/log/filebeat/test-service:ro
