filebeat.config:
  modules:
    path: ./modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    - '/var/log/filebeat/**/*.log'
  exclude_lines: ['^ERR']

output.logstash:
  enabled: true
  hosts: 
    - "${LOGSTASH_HOST:logstash-host.com}:9202"
    - "${LOGSTASH_HOST:logstash-host.com}:9203"
  loadbalance: true
  worker: 2
  compression_level: 3
  escape_html: false
  ssl.enabled: false

  #output.console:
  #  pretty: true

processors:
  - add_fields:
      target: 'service'
      fields:
        name: ${SERVICE_NAME}
        version: ${SERVICE_VERSION} 
        environment: ${SERVICE_ENVIRONMENT}
